simpleblog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts

end

simpleblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

simpleblog/app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true,	
		length: {minimum: 5}					
end

simpleblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

simpleblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us:'
		@content = 'This is the about page.'
	end
end

simpleblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		#render plain: params[:post].inspect
		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private def post_params
		params.require(:post).permit(:title, :body)
	end
end

simpleblog/app/helpers/application_helper.rb
module ApplicationHelper
end

simpleblog/app/helpers/pages_helper.rb
module PagesHelper
end

simpleblog/app/helpers/posts_helper.rb
module PostsHelper
end

simpleblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="navbar">
  	<ul class="navbar-nav">
  		<li><%= link_to "Home", home_path %></li>
  	</ul>
  	<ul class="navbar-nav">
  		<li><%= link_to "Create Post", new_post_path %></li>
  	</ul>
  </div>


    <%= yield %>
  </body>
</html>

simpleblog/app/views/pages/about.html.erb
<h1><%=@title%></h1>
<p><%=@content%></p>

simpleblog/app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

simpleblog/app/views/posts/index.html.erb
<h1>Simple Blog Posts</h1>
<% @posts.each do |post| %>
	<h3><%= post.title %></h3>
	<p><%= post.body %></p>
	<%= link_to "Read More", post_path(post) %>
<% end %>

simpleblog/app/views/posts/new.html.erb
<h1>Add post</h1>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

simpleblog/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>